stages:
  - build
  - docker-build
  - test
  - analyze


build:
  stage: build
  script:
    - ./gradlew assemble


test:
  stage: test
  script:
    - ./gradlew test

jacoco:
  stage: test
  script:
    - ./gradlew jacocoTestReport
  artifacts:
    paths:
      - build/reports/jacoco/test/html/

docker-build:
  stage: docker-build
  image: docker:19.03.12
  services:
    - docker:dind
  script:
    - docker build -t my-local-app-image .
  only:
    - master
  tags:
    - local

sonarqube:
  stage: analyze
  image: openjdk:latest
  script:
    - ./gradlew sonarqube -Dsonar.login=$SONAR_TOKEN
  allow_failure: true
  only:
    - master

variables:
  SONAR_TOKEN: "sqp_9683da089acf9a5f3741419475dd952d79c6d9f7"
