
  # Disable the Gradle daemon for Continuous Integration servers as correctness
  # is usually a priority over speed in CI environments. Using a fresh
  # runtime for each build is more reliable since the runtime is completely
  # isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  SONAR_TOKEN: "sqp_4eb3d38d7b57444bf4db6b8a87e97c98f74d5212"
stages:
  - build
  - docker-build
  - test
  - analyze

build:
  stage: build
  script:
    - ./gradlew assemble

test:
  stage: test
  script:
    - ./gradlew test

jacoco:
  stage: test
  script:
    - ./gradlew jacocoTestReport
  artifacts:
    paths:
      - build/reports/jacoco/test/html/

docker-build:
  stage: docker-build
  image: docker:19.03.12
  services:
    - docker:dind
  script:
    - docker build -t my-local-app-image .
  only:
    - master
  tags:
    - local

sonarqube:
  stage: analyze
  image: openjdk:latest
  script:
    - ./gradlew sonarqube -Dsonar.projectKey=IndivS4 -Dsonar.projectName=IndivS4 -Dsonar.host.url=http://localhost:9000 -Dsonar.login=$SONAR_TOKEN
  allow_failure: true
  only:
    - master


