variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  SONAR_TOKEN: "sqb_f5203242dd094169b447143c8050ac53fd591a3b"

stages:
  - build
  - test
  - analyze

build:
  stage: build
  script:
    - ./gradlew assemble

test:
  stage: test
  script:
    - ./gradlew test

jacoco:
  stage: test
  script:
    - ./gradlew jacocoTestReport
  artifacts:
    paths:
      - build/reports/jacoco/test/html/
      - build/reports/jacoco/test/jacocoTestReport.xml

sonarqube:
  stage: analyze
  image: openjdk:latest
  script:
    ./gradlew -Dsonar.projectKey=IndivS4 -Dsonar.projectName=IndivS4 -Dsonar.host.url=http://localhost:9000 -Dsonar.login=$SONAR_TOKEN -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml sonarqube

  allow_failure: true
  only:
    - master
