variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  SONAR_TOKEN: "sqb_f5203242dd094169b447143c8050ac53fd591a3b"

stages:
  - build
  - test
  - build_image
  - sonar

build:
  stage: build
  script:
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/*.jar

test:
  stage: test
  script:
    - ./gradlew test jacocoTestReport
  artifacts:
    paths:
      - build/reports/jacoco/test/jacocoTestReport.xml

build_image:
  stage: build_image
  needs: ["build"]
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker info
    - docker login -u stefanpricopi -p dt8W/c!Kd%sWqnL
  script:
    - docker build -t stefanpricopi/your-repo:latest .
    - docker push stefanpricopi/your-repo:latest

sonar:
  stage: sonar
  script:
    - ./gradlew sonarqube -Dsonar.host.url="http://localhost:9000" -Dsonar.login="$SONAR_TOKEN" -Dsonar.java.binaries="src/main/java" -Dsonar.jacoco.reportPaths="build/reports/jacoco/test/jacocoTestReport.xml"
  dependencies:
    - test
  allow_failure: true
