image: openjdk:17

stages:
  - build
  - test

build:
  stage: build
  script:
    - ./gradlew assemble --stacktrace

test:
  stage: test
  script:
    - java -version  # Print Java version
    - ./gradlew test
