stages:
  - build
  - test
  - build_image
  - sonar

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build:
  stage: build
  script:
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/*.jar

test:
  stage: test
  script:
    - ./gradlew test jacocoTestReport
  artifacts:
    paths:
      - build/reports/jacoco/test/jacocoTestReport.xml

build_image:
  stage: build_image
  needs: ["build"]
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker info
    - docker login -u stefanpricopi -p dt8W/c!Kd%sWqnL
  script:
    - docker build -t stefanpricopi/your-repo:latest .
    - docker push stefanpricopi/your-repo:latest

sonar:
  stage: sonar
  script:
    - ./gradlew sonarqube -Dsonar.projectKey=test11 -Dsonar.projectName=test1 -Dsonar.host.url=http://localhost:9000 -Dsonar.login=sqp_7b1ccd0155f7745a1a98b40f4c57bd4b78bd31e4 -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
  dependencies:
    - test
  allow_failure: true
